---
title: Site title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: ''
baseurl: ''
encoding: utf-8
markdown: kramdown
permalink: pretty
